/** The explanation of the Phase 1 run (docs/DEMO-PROOF.md), read from the API on 2026-09-30 and kept as a fixture. */

import type { RunExplanationView } from "@/lib/types";

export const EXPLANATION_E5A20E22: RunExplanationView = {
  runId: "e5a20e2283e8416e",
  question: "May either party terminate this agreement for convenience, and on what notice?",
  stage: "complete",
  reason: null,
  reading: {
    documentId: "7b8ed34fd627491c",
    documentName: "MTI-Reseller-Agreement.docx",
    documentSha256: "d510d1d71a7b6629636d424c8756dbf24a02808d8b93c97e9f6842bfcb097f5a",
    readerVersion: "v4",
    pages: 1,
    sections: 6,
    numberedSections: 0,
    trackedChanges: 0,
    hiddenRuns: 0,
    coverage: {
      schemaVersion: 1,
      readerVersion: "v4",
      source: "persisted",
      parts: [
        {
          part: "main_body",
          status: "read",
          count: 0,
          note: "paragraphs and tables of the body, in document order",
        },
        {
          part: "tables",
          status: "absent",
          count: 0,
          note: "",
        },
        {
          part: "tracked_insertions",
          status: "absent",
          count: 0,
          note: "",
        },
        {
          part: "tracked_deletions",
          status: "absent",
          count: 0,
          note: "",
        },
        {
          part: "move_revisions",
          status: "absent",
          count: 0,
          note: "",
        },
        {
          part: "hidden_runs",
          status: "absent",
          count: 0,
          note: "",
        },
        {
          part: "style_hidden_text",
          status: "unknown",
          count: 0,
          note: "text hidden through a style is kept; the reader does not resolve styles",
        },
        {
          part: "headers",
          status: "absent",
          count: 0,
          note: "",
        },
        {
          part: "footers",
          status: "absent",
          count: 0,
          note: "",
        },
        {
          part: "footnotes",
          status: "absent",
          count: 0,
          note: "",
        },
        {
          part: "endnotes",
          status: "absent",
          count: 0,
          note: "",
        },
        {
          part: "comments",
          status: "absent",
          count: 0,
          note: "",
        },
        {
          part: "content_controls",
          status: "absent",
          count: 0,
          note: "",
        },
        {
          part: "fields",
          status: "absent",
          count: 0,
          note: "",
        },
        {
          part: "automatic_numbering",
          status: "absent",
          count: 0,
          note: "",
        },
        {
          part: "embedded_objects",
          status: "absent",
          count: 0,
          note: "",
        },
        {
          part: "external_chunks",
          status: "absent",
          count: 0,
          note: "",
        },
      ],
    },
    notRead: [],
    recordedSectionsHash: "eb2a7646f15338488d8e7f284482fbd328df249ac8990452fa677991529b3f16",
  },
  retrieval: [
    {
      rank: 1,
      label: "sec_0",
      sectionId: "a5e6a395fcb548dc",
      number: "",
      heading: "EXHIBIT 10.102 (part 1)",
      characters: 5993,
      sliceStart: 0,
      sliceEnd: 5000,
      truncated: true,
    },
    {
      rank: 2,
      label: "sec_3",
      sectionId: "f7968268325b4f78",
      number: "",
      heading: "EXHIBIT 10.102 (part 4)",
      characters: 5686,
      sliceStart: 0,
      sliceEnd: 5000,
      truncated: true,
    },
    {
      rank: 3,
      label: "sec_1",
      sectionId: "1724cb054c624fec",
      number: "",
      heading: "EXHIBIT 10.102 (part 2)",
      characters: 5788,
      sliceStart: 0,
      sliceEnd: 5000,
      truncated: true,
    },
    {
      rank: 4,
      label: "sec_4",
      sectionId: "cb7670c83acc43d7",
      number: "",
      heading: "EXHIBIT 10.102 (part 5)",
      characters: 5948,
      sliceStart: 0,
      sliceEnd: 5000,
      truncated: true,
    },
    {
      rank: 5,
      label: "sec_2",
      sectionId: "4d9d9abfac87432e",
      number: "",
      heading: "EXHIBIT 10.102 (part 3)",
      characters: 5960,
      sliceStart: 0,
      sliceEnd: 5000,
      truncated: true,
    },
    {
      rank: 6,
      label: "sec_5",
      sectionId: "d8f3ebfb3b6e401b",
      number: "",
      heading: "EXHIBIT 10.102 (part 6)",
      characters: 3329,
      sliceStart: 0,
      sliceEnd: 3329,
      truncated: false,
    },
  ],
  reconstruction: {
    reconstructable: true,
    problem: null,
    recordedInputSha256: "f5991f58975995980651a9941650a0695750957d32e747164ac0f697240e7591",
    rebuiltInputSha256: "f5991f58975995980651a9941650a0695750957d32e747164ac0f697240e7591",
    windowChars: 5000,
    charactersOutsideContext: 4375,
    question: "May either party terminate this agreement for convenience, and on what notice?",
    hasGuidance: true,
    guidanceText: "We require at least 90 days' written notice for termination for convenience. Anything shorter needs review.",
    promptVersion: "answer-v2",
    promptHash: "9dbeb12a871ece17872898b2168313a113ab03d7178c263081b5a86d5a1fc954",
    model: "qwen3:8b",
    options: {
      model: "qwen3:8b",
      num_ctx: 16384,
      retrieval_k: 6,
      seed: 42,
      temperature: 0.0,
    },
    queueNote: null,
  },
  proposals: [
    {
      ordinal: 0,
      topic: "Termination for convenience",
      conclusion: "Either party may terminate this agreement for convenience with 60 days' written notice.",
      statusHint: "pass",
      observed: "60 days' written notice",
      required: "at least 90 days",
      guidanceReference: "We require at least 90 days' written notice for termination for convenience. Anything shorter needs review.",
      suggestedPosition: "90 days' written notice",
      evidence: [
        {
          citedLabel: "sec_4",
          quote:
            "4.1 TERMINATION WITHOUT CAUSE. Either party may terminate this Agreement without cause upon sixty (60) days prior written notice to the other party.",
        },
      ],
    },
  ],
  proposalsProblem: null,
  findings: [
    {
      id: "afa60a7574984690",
      ordinal: 0,
      topic: "Termination for convenience",
      conclusion: "Either party may terminate this agreement for convenience with 60 days' written notice.",
      status: "needs_review",
      shown: true,
      sourceMatches: [
        {
          quote:
            "4.1 TERMINATION WITHOUT CAUSE. Either party may terminate this Agreement without cause upon sixty (60) days prior written notice to the other party.",
          citedLabel: "sec_4",
          locatedSectionId: "a5e6a395fcb548dc",
          locatedLabel: "sec_0",
          locatedHeading: "EXHIBIT 10.102 (part 1)",
          verified: true,
          method: "relocated:exact",
          matchCount: 1,
          start: 4136,
          end: 4284,
          relocated: true,
          insideModelVisibleContext: true,
        },
      ],
      recordedPolicyEvaluation: {
        status: "needs_review",
        statusSource: "computed_days",
        statusReason: "the contract provides 60 calendar days; the guidance requires at least 90 calendar days",
        deterministic: true,
        summary: "the status was computed by code from the duration in the verified quote and the rule in the guidance",
      },
      review: {
        verdict: "confirmed",
        reviewer: "Pavan",
        note: null,
        at: "2026-09-30T22:25:57.788421+00:00",
      },
    },
  ],
  reproducibility: {
    runId: "e5a20e2283e8416e",
    documentId: "7b8ed34fd627491c",
    documentSha256: "d510d1d71a7b6629636d424c8756dbf24a02808d8b93c97e9f6842bfcb097f5a",
    readerVersion: "v4",
    guidanceSha256: "33f5a9af540d87e19d29eabd0fc6dd2734b8ca669caddd808319610c77ffe403",
    promptVersion: "answer-v2",
    promptHash: "9dbeb12a871ece17872898b2168313a113ab03d7178c263081b5a86d5a1fc954",
    recordedInputSha256: "f5991f58975995980651a9941650a0695750957d32e747164ac0f697240e7591",
    inputMatches: true,
    evidencePackPath: "/api/runs/e5a20e2283e8416e/evidence-pack",
  },
};
