/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/batches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Batches */
        get: operations["batches_api_batches_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/batches/{batch_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Batch */
        get: operations["batch_api_batches__batch_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/batches/{batch_id}/values.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Batch Values Csv
         * @description One row per document and field: the value, its status, the citation and how it was located, and the run.
         */
        get: operations["batch_values_csv_api_batches__batch_id__values_csv_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Documents */
        get: operations["list_documents_api_documents_get"];
        put?: never;
        /**
         * Upload Document
         * @description 201 with a new document, or 200 with the stored document that has exactly these bytes.
         */
        post: operations["upload_document_api_documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Document */
        get: operations["get_document_api_documents__document_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/engineering/citations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Citations
         * @description How often the model's quotes were found, by which method, and how often a finding was withheld.
         */
        get: operations["citations_api_engineering_citations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/engineering/experiments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Experiments */
        get: operations["experiments_api_engineering_experiments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/engineering/families": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Families
         * @description Structural families among the labeled corpus documents at a threshold, with the evaluation against the labels.
         */
        get: operations["families_api_engineering_families_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/engineering/goldens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Goldens
         * @description The golden set with each golden's run and verdict per prompt version, and the latest comparison.
         */
        get: operations["goldens_api_engineering_goldens_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/findings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Findings */
        get: operations["list_findings_api_findings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/findings/{finding_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Review
         * @description Record a person's decision. 201 when it changed the state, 200 when it repeated it; `cleared` undoes.
         */
        post: operations["review_api_findings__finding_id__review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/guidance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Guidance
         * @description 201 with a new guidance record, or 200 with the record that already holds these words.
         */
        post: operations["create_guidance_api_guidance_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/guidance/{guidance_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Guidance */
        get: operations["get_guidance_api_guidance__guidance_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/memos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Memo
         * @description 201 with a memo for the run's current review state, or 200 with the one already written under it. A review
         *     after a memo makes the next request write a new memo; the earlier one is kept as it was.
         */
        post: operations["create_memo_api_memos_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/memos/{memo_id}/docx": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Memo As Docx */
        get: operations["memo_as_docx_api_memos__memo_id__docx_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/memos/{memo_id}/html": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Memo As Html */
        get: operations["memo_as_html_api_memos__memo_id__html_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_api_runs_get"];
        put?: never;
        /**
         * Create Run
         * @description 202 with a new run, or 200 with the running or completed run that already has these inputs.
         */
        post: operations["create_run_api_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/detail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run Detail */
        get: operations["get_run_detail_api_runs__run_id__detail_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Run Events
         * @description Stage transitions only. Replays what already happened, then streams until the run ends, by this process's
         *     bus or, at the latest, one heartbeat after the record says it ended.
         */
        get: operations["run_events_api_runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/evidence-pack": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Evidence Pack
         * @description A zip with the original bytes, the canonical sections, the run record, every located span and a stdlib verify.py.
         */
        get: operations["evidence_pack_api_runs__run_id__evidence_pack_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BatchField */
        BatchField: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Question */
            question: string;
        };
        /** BatchOut */
        BatchOut: {
            /**
             * Answered
             * @default 0
             */
            answered: number;
            /** Concurrency */
            concurrency: number;
            /** Corpus */
            corpus: string;
            /** Documents */
            documents: number;
            /** Documentsperminute */
            documentsPerMinute?: number | null;
            /**
             * Failedrunsbyreason
             * @default {}
             */
            failedRunsByReason: {
                [key: string]: number;
            };
            /**
             * Fields
             * @default []
             */
            fields: components["schemas"]["BatchField"][];
            /**
             * Findings
             * @default 0
             */
            findings: number;
            /** Finishedat */
            finishedAt?: string | null;
            /** Id */
            id: string;
            /**
             * Invalidoutputruns
             * @default 0
             */
            invalidOutputRuns: number;
            /** Model */
            model: string;
            /** Modellatencymeanms */
            modelLatencyMeanMs?: number | null;
            /** Modellatencyp50Ms */
            modelLatencyP50Ms?: number | null;
            /** Modellatencyp95Ms */
            modelLatencyP95Ms?: number | null;
            /**
             * Promptversion
             * @default
             */
            promptVersion: string;
            /**
             * Providererrorruns
             * @default 0
             */
            providerErrorRuns: number;
            /** Requested */
            requested: number;
            /**
             * Retries
             * @default 0
             */
            retries: number;
            /**
             * Rows
             * @default []
             */
            rows: components["schemas"]["BatchRow"][];
            /**
             * Runscreated
             * @default 0
             */
            runsCreated: number;
            /**
             * Runsreused
             * @default 0
             */
            runsReused: number;
            /**
             * Spans
             * @default 0
             */
            spans: number;
            /** Startedat */
            startedAt: string;
            /** Task */
            task: string;
            /**
             * Taskdescription
             * @default
             */
            taskDescription: string;
            /** Valuesperminute */
            valuesPerMinute?: number | null;
            /**
             * Verifiedspans
             * @default 0
             */
            verifiedSpans: number;
            /**
             * Wallminutes
             * @default 0
             */
            wallMinutes: number;
            /**
             * Withheldfindings
             * @default 0
             */
            withheldFindings: number;
        };
        /** BatchRow */
        BatchRow: {
            /** Documentid */
            documentId: string;
            /** Documentname */
            documentName: string;
            /** Values */
            values: {
                [key: string]: components["schemas"]["BatchValue"];
            };
        };
        /** BatchSummary */
        BatchSummary: {
            /** Concurrency */
            concurrency: number;
            /** Corpus */
            corpus: string;
            /** Documents */
            documents: number;
            /** Finishedat */
            finishedAt?: string | null;
            /** Id */
            id: string;
            /** Model */
            model: string;
            /**
             * Promptversion
             * @default
             */
            promptVersion: string;
            /** Requested */
            requested: number;
            /** Startedat */
            startedAt: string;
            /** Task */
            task: string;
        };
        /**
         * BatchValue
         * @description What a batch extracted for one document and field: the first finding whose citation verified, or why there is none.
         */
        BatchValue: {
            /** Citation */
            citation?: string | null;
            /** Method */
            method?: string | null;
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "answered" | "not_found" | "withheld" | "failed" | "in_progress";
            /** Reason */
            reason?: ("insufficient_evidence" | "citations_unverified" | "invalid_output" | "provider_error" | "internal_error") | null;
            /** Runid */
            runId: string;
            /** Status */
            status?: ("pass" | "needs_review" | "missing" | "unresolved") | null;
            /** Value */
            value?: string | null;
        };
        /** Body_upload_document_api_documents_post */
        Body_upload_document_api_documents_post: {
            /** File */
            file: string;
        };
        /**
         * CandidateOut
         * @description A section handed to the model, by the label it cites.
         */
        CandidateOut: {
            /**
             * Heading
             * @default
             */
            heading: string;
            /** Label */
            label: string;
            /**
             * Number
             * @default
             */
            number: string;
            /** Sectionid */
            sectionId: string;
        };
        /**
         * CitationRecordOut
         * @description What the verifier did across every run where the model answered, counted from the records.
         */
        CitationRecordOut: {
            /**
             * Bymethod
             * @default {}
             */
            byMethod: {
                [key: string]: number;
            };
            /** Completeruns */
            completeRuns: number;
            /** Findings */
            findings: number;
            /** Firstrunat */
            firstRunAt?: string | null;
            /** Lastrunat */
            lastRunAt?: string | null;
            /** Runs */
            runs: number;
            /** Spans */
            spans: number;
            /** Unresolvedruns */
            unresolvedRuns: number;
            /** Verifiedspans */
            verifiedSpans: number;
            /** Withheldfindings */
            withheldFindings: number;
        };
        /**
         * CoverageOut
         * @description What the reading did with one part of the file: read, accepted, excluded, partial, omitted, absent or unknown.
         */
        CoverageOut: {
            /**
             * Count
             * @default 0
             */
            count: number;
            /**
             * Note
             * @default
             */
            note: string;
            /** Part */
            part: string;
            /** Status */
            status: string;
        };
        /**
         * CoverageReport
         * @description A reading's coverage with its provenance. persisted: recorded by the reading at upload. reconstructed: computed later
         *     from the stored bytes under the same reader version; the same facts, not captured at the time.
         */
        CoverageReport: {
            /** Parts */
            parts: components["schemas"]["CoverageOut"][];
            /** Readerversion */
            readerVersion: string;
            /** Schemaversion */
            schemaVersion: number;
            /**
             * Source
             * @enum {string}
             */
            source: "persisted" | "reconstructed";
        };
        /** DocumentOut */
        DocumentOut: {
            coverage?: components["schemas"]["CoverageReport"] | null;
            /**
             * Createdat
             * @default
             */
            createdAt: string;
            /** Hiddenruns */
            hiddenRuns?: number | null;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Pages */
            pages: number | null;
            /** Parsems */
            parseMs?: number | null;
            /** Parserversion */
            parserVersion?: string | null;
            /**
             * Reused
             * @default false
             */
            reused: boolean;
            /** Sections */
            sections: components["schemas"]["SectionOut"][];
            /** Sha256 */
            sha256: string | null;
            /** Trackedchanges */
            trackedChanges?: number | null;
        };
        /** DocumentSummary */
        DocumentSummary: {
            /** Createdat */
            createdAt: string;
            /**
             * Findings
             * @default 0
             */
            findings: number;
            /** Id */
            id: string;
            /** Lastrunat */
            lastRunAt?: string | null;
            /** Name */
            name: string;
            /** Pages */
            pages: number | null;
            /**
             * Reviewedfindings
             * @default 0
             */
            reviewedFindings: number;
            /** Sections */
            sections: number;
        };
        /** ExperimentPage */
        ExperimentPage: {
            /** Author */
            author?: string | null;
            /** Branch */
            branch?: string | null;
            /** Period */
            period?: string | null;
            /** Repourl */
            repoUrl?: string | null;
            /** Subtitle */
            subtitle?: string | null;
            /** Title */
            title?: string | null;
        };
        /** ExperimentRecord */
        ExperimentRecord: {
            /** Code */
            code: string;
            /** Date */
            date: string;
            /**
             * Expected
             * @default
             */
            expected: string;
            /** Gate */
            gate: string;
            /** Id */
            id: string;
            /** Observed */
            observed: string;
            /** Title */
            title: string;
        };
        /** ExperimentsOut */
        ExperimentsOut: {
            /** Available */
            available: boolean;
            /**
             * Baselines
             * @default []
             */
            baselines: components["schemas"]["ExperimentRecord"][];
            /**
             * Board
             * @default []
             */
            board: components["schemas"]["ExperimentRecord"][];
            /** Detail */
            detail?: string | null;
            /** Generatedat */
            generatedAt?: string | null;
            /** @default {} */
            page: components["schemas"]["ExperimentPage"];
            /** Pageurl */
            pageUrl?: string | null;
            /** Repohead */
            repoHead?: string | null;
            /** Source */
            source: string | null;
        };
        /** FamiliesOut */
        FamiliesOut: {
            /** Available */
            available: boolean;
            /** Detail */
            detail?: string | null;
            /**
             * Documents
             * @default 0
             */
            documents: number;
            /**
             * Evaluations
             * @default []
             */
            evaluations: components["schemas"]["FamilyEvaluation"][];
            /**
             * Families
             * @default []
             */
            families: components["schemas"]["FamilyOut"][];
            /**
             * Missing
             * @default []
             */
            missing: string[];
            /**
             * Note
             * @default
             */
            note: string;
            /**
             * Pairs
             * @default []
             */
            pairs: components["schemas"]["FamilyPair"][];
            /** Threshold */
            threshold: number;
            /**
             * Weights
             * @default {}
             */
            weights: {
                [key: string]: number;
            };
        };
        /** FamilyEvaluation */
        FamilyEvaluation: {
            /** Bestf1 */
            bestF1: number;
            /** Bestthreshold */
            bestThreshold: number;
            /**
             * Description
             * @default
             */
            description: string;
            /** F1 */
            f1: number;
            /** Labelset */
            labelSet: string;
            /**
             * Labeledpairs
             * @default 0
             */
            labeledPairs: number;
            /** Precision */
            precision: number;
            /** Recall */
            recall: number;
            /**
             * Sweep
             * @default []
             */
            sweep: components["schemas"]["FamilyThresholdPoint"][];
        };
        /** FamilyOut */
        FamilyOut: {
            /** Maxsimilarity */
            maxSimilarity?: number | null;
            /** Members */
            members: string[];
            /** Minsimilarity */
            minSimilarity?: number | null;
            /**
             * Titles
             * @default []
             */
            titles: string[];
        };
        /** FamilyPair */
        FamilyPair: {
            /** A */
            a: string;
            /** B */
            b: string;
            /** Combined */
            combined: number;
            /** Headings */
            headings: number;
            /**
             * Labeled
             * @default false
             */
            labeled: boolean;
            /** Shingles */
            shingles: number;
            /** Terms */
            terms: number;
        };
        /** FamilyThresholdPoint */
        FamilyThresholdPoint: {
            /** F1 */
            f1: number;
            /** Precision */
            precision: number;
            /** Recall */
            recall: number;
            /** Threshold */
            threshold: number;
        };
        /** FindingOut */
        FindingOut: {
            /** Conclusion */
            conclusion: string;
            /**
             * Evidencekind
             * @default passage
             * @enum {string}
             */
            evidenceKind: "passage" | "coverage";
            /** Guidancereference */
            guidanceReference: string | null;
            /** Id */
            id: string;
            /** Observed */
            observed: string | null;
            /** Required */
            required: string | null;
            review?: components["schemas"]["ReviewOut"] | null;
            /** Spans */
            spans: components["schemas"]["SpanOut"][];
            /**
             * Status
             * @enum {string}
             */
            status: "pass" | "needs_review" | "missing" | "unresolved";
            /**
             * Statussource
             * @default
             */
            statusSource: string;
            /** Suggestedposition */
            suggestedPosition: string | null;
            /** Topic */
            topic: string;
        };
        /** FindingRecord */
        FindingRecord: {
            /**
             * Citations
             * @default []
             */
            citations: string[];
            /** Conclusion */
            conclusion: string;
            /** Createdat */
            createdAt: string;
            /** Documentid */
            documentId: string;
            /** Documentname */
            documentName: string;
            /**
             * Evidencekind
             * @default passage
             * @enum {string}
             */
            evidenceKind: "passage" | "coverage";
            /**
             * Hasguidance
             * @default false
             */
            hasGuidance: boolean;
            /** Id */
            id: string;
            /** Question */
            question: string;
            review?: components["schemas"]["ReviewOut"] | null;
            /** Runid */
            runId: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pass" | "needs_review" | "missing" | "unresolved";
            /** Topic */
            topic: string;
            /** Verifiedspans */
            verifiedSpans: number;
        };
        /** FindingReviewOut */
        FindingReviewOut: {
            /** Findingid */
            findingId: string;
            review?: components["schemas"]["ReviewOut"] | null;
        };
        /** GoldenCategoryCount */
        GoldenCategoryCount: {
            /** Category */
            category: string;
            /** Passes */
            passes: number;
            /** Recorded */
            recorded: number;
        };
        /** GoldenCompareOut */
        GoldenCompareOut: {
            /** Base */
            base: string;
            /** Better */
            better: number;
            /** Changed */
            changed: number;
            /** Head */
            head: string;
            /** Latencydeltams */
            latencyDeltaMs?: number | null;
            /** Rows */
            rows: components["schemas"]["GoldenDelta"][];
            /** Same */
            same: number;
            /** Worse */
            worse: number;
        };
        /** GoldenDelta */
        GoldenDelta: {
            /**
             * Base
             * @enum {string}
             */
            base: "pass" | "fail" | "missing";
            /**
             * Change
             * @enum {string}
             */
            change: "better" | "worse" | "same";
            /** Changed */
            changed: boolean;
            /** Goldenid */
            goldenId: string;
            /**
             * Head
             * @enum {string}
             */
            head: "pass" | "fail" | "missing";
            /** Note */
            note: string;
        };
        /** GoldenExpectation */
        GoldenExpectation: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "present" | "absent";
            /**
             * Sections
             * @default []
             */
            sections: string[];
            /** Status */
            status?: ("pass" | "needs_review") | null;
        };
        /** GoldenOut */
        GoldenOut: {
            /**
             * Category
             * @default
             */
            category: string;
            expect: components["schemas"]["GoldenExpectation"];
            /** Guidance */
            guidance?: string | null;
            /** Id */
            id: string;
            /** Question */
            question: string;
            /** Why */
            why: string;
        };
        /** GoldenPromptOut */
        GoldenPromptOut: {
            /**
             * Bycategory
             * @default []
             */
            byCategory: components["schemas"]["GoldenCategoryCount"][];
            /** Hash */
            hash: string;
            /** Meanlatencyms */
            meanLatencyMs?: number | null;
            /** Passes */
            passes: number;
            /** Recorded */
            recorded: number;
            /** Runs */
            runs: components["schemas"]["GoldenRunOut"][];
            /** Version */
            version: string;
        };
        /**
         * GoldenRunOut
         * @description One golden under one prompt version: the run found by fingerprint and the verdict code gave it.
         */
        GoldenRunOut: {
            /** Because */
            because: string;
            /**
             * Cited
             * @default []
             */
            cited: string[];
            /** Goldenid */
            goldenId: string;
            /** Latencyms */
            latencyMs?: number | null;
            /** Reason */
            reason?: ("insufficient_evidence" | "citations_unverified" | "invalid_output" | "provider_error" | "internal_error") | null;
            /** Runid */
            runId?: string | null;
            /** Stage */
            stage?: ("reading" | "finding_evidence" | "checking" | "verifying" | "complete" | "unresolved" | "failed") | null;
            /**
             * Statuses
             * @default []
             */
            statuses: ("pass" | "needs_review" | "missing" | "unresolved")[];
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "pass" | "fail" | "missing";
        };
        /** GoldensOut */
        GoldensOut: {
            /** Available */
            available: boolean;
            /**
             * Categories
             * @default {}
             */
            categories: {
                [key: string]: string;
            };
            compare?: components["schemas"]["GoldenCompareOut"] | null;
            /** Detail */
            detail?: string | null;
            /** Documentid */
            documentId?: string | null;
            /**
             * Documentname
             * @default
             */
            documentName: string;
            /** Documentsha256 */
            documentSha256?: string | null;
            /**
             * Goldens
             * @default []
             */
            goldens: components["schemas"]["GoldenOut"][];
            /**
             * Prompts
             * @default []
             */
            prompts: components["schemas"]["GoldenPromptOut"][];
            /**
             * Rules
             * @default
             */
            rules: string;
            /** Setsha256 */
            setSha256: string;
        };
        /** GuidanceIn */
        GuidanceIn: {
            /** Text */
            text: string;
        };
        /** GuidanceOut */
        GuidanceOut: {
            /** Id */
            id: string;
            /** Sha256 */
            sha256: string;
            /** Text */
            text: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthOut */
        HealthOut: {
            /** Detail */
            detail: string;
            /** Model */
            model: string;
            /** Ok */
            ok: boolean;
            /** Provider */
            provider: string;
        };
        /** MemoIn */
        MemoIn: {
            /** Runid */
            runId: string;
        };
        /** MemoOut */
        MemoOut: {
            /** Docxsha256 */
            docxSha256: string;
            /** Docxurl */
            docxUrl: string;
            /** Htmlurl */
            htmlUrl: string;
            /** Id */
            id: string;
            /**
             * Reviewhead
             * @default
             */
            reviewHead: string;
            /** Runid */
            runId: string;
        };
        /** ReviewIn */
        ReviewIn: {
            /** Note */
            note?: string | null;
            /** Reviewer */
            reviewer: string;
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "confirmed" | "dismissed" | "cleared";
        };
        /**
         * ReviewOut
         * @description A person's current decision on a finding; absent when unreviewed or cleared.
         */
        ReviewOut: {
            /** At */
            at: string;
            /** Note */
            note?: string | null;
            /** Reviewer */
            reviewer: string;
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "confirmed" | "dismissed";
        };
        /** RunDetail */
        RunDetail: {
            /** Candidates */
            candidates: components["schemas"]["CandidateOut"][];
            /** Createdat */
            createdAt: string;
            /** Documentid */
            documentId: string;
            /**
             * Documentname
             * @default
             */
            documentName: string;
            /** Documentparsems */
            documentParseMs?: number | null;
            /** Documentsha256 */
            documentSha256: string;
            /** Error */
            error: string | null;
            /** Findings */
            findings: components["schemas"]["FindingOut"][];
            /** Finishedat */
            finishedAt: string | null;
            /** Guidanceid */
            guidanceId: string | null;
            /** Guidancesha256 */
            guidanceSha256: string | null;
            /** Guidancetext */
            guidanceText?: string | null;
            /**
             * Hasguidance
             * @default false
             */
            hasGuidance: boolean;
            /** Id */
            id: string;
            /** Inputtokens */
            inputTokens: number | null;
            /** Latencyms */
            latencyMs: number | null;
            /** Model */
            model: string;
            /** Note */
            note: string | null;
            /** Options */
            options: {
                [key: string]: number | string;
            };
            /** Outputtokens */
            outputTokens: number | null;
            /** Prompthash */
            promptHash: string;
            /** Promptversion */
            promptVersion: string;
            /** Provider */
            provider: string;
            /** Question */
            question: string;
            /** Rawoutput */
            rawOutput: string | null;
            /** Reason */
            reason?: ("insufficient_evidence" | "citations_unverified" | "invalid_output" | "provider_error" | "internal_error") | null;
            /**
             * Reused
             * @default false
             */
            reused: boolean;
            /**
             * Reviewhead
             * @default
             */
            reviewHead: string;
            /** Routingreason */
            routingReason?: string | null;
            /**
             * Stage
             * @enum {string}
             */
            stage: "reading" | "finding_evidence" | "checking" | "verifying" | "complete" | "unresolved" | "failed";
            /** Stages */
            stages: components["schemas"]["StageOut"][];
            /** Task */
            task?: string | null;
            /**
             * Totalspans
             * @default 0
             */
            totalSpans: number;
            /**
             * Verifiedspans
             * @default 0
             */
            verifiedSpans: number;
            /**
             * Withheld
             * @default []
             */
            withheld: components["schemas"]["FindingOut"][];
        };
        /** RunIn */
        RunIn: {
            /** Documentid */
            documentId: string;
            /** Guidanceid */
            guidanceId?: string | null;
            /** Question */
            question: string;
        };
        /** RunOut */
        RunOut: {
            /** Error */
            error: string | null;
            /** Findings */
            findings: components["schemas"]["FindingOut"][];
            /** Guidancetext */
            guidanceText?: string | null;
            /**
             * Hasguidance
             * @default false
             */
            hasGuidance: boolean;
            /** Id */
            id: string;
            /** Latencyms */
            latencyMs: number | null;
            /** Model */
            model: string;
            /** Note */
            note: string | null;
            /** Prompthash */
            promptHash: string;
            /** Promptversion */
            promptVersion: string;
            /** Question */
            question: string;
            /** Reason */
            reason?: ("insufficient_evidence" | "citations_unverified" | "invalid_output" | "provider_error" | "internal_error") | null;
            /**
             * Reused
             * @default false
             */
            reused: boolean;
            /**
             * Reviewhead
             * @default
             */
            reviewHead: string;
            /**
             * Stage
             * @enum {string}
             */
            stage: "reading" | "finding_evidence" | "checking" | "verifying" | "complete" | "unresolved" | "failed";
            /**
             * Withheld
             * @default []
             */
            withheld: components["schemas"]["FindingOut"][];
        };
        /** RunSummary */
        RunSummary: {
            /** Createdat */
            createdAt: string;
            /** Documentid */
            documentId: string;
            /** Documentname */
            documentName: string;
            /** Findings */
            findings: number;
            /** Hasguidance */
            hasGuidance: boolean;
            /** Id */
            id: string;
            /** Latencyms */
            latencyMs: number | null;
            /** Model */
            model: string;
            /** Prompthash */
            promptHash: string;
            /** Promptversion */
            promptVersion: string;
            /** Question */
            question: string;
            /** Reason */
            reason?: ("insufficient_evidence" | "citations_unverified" | "invalid_output" | "provider_error" | "internal_error") | null;
            /**
             * Stage
             * @enum {string}
             */
            stage: "reading" | "finding_evidence" | "checking" | "verifying" | "complete" | "unresolved" | "failed";
        };
        /** SectionOut */
        SectionOut: {
            /** Heading */
            heading: string;
            /** Id */
            id: string;
            /** Number */
            number: string;
            /** Text */
            text: string;
        };
        /** SpanOut */
        SpanOut: {
            /**
             * Citedsectionlabel
             * @default
             */
            citedSectionLabel: string;
            /** End */
            end: number;
            /** Matchcount */
            matchCount?: number | null;
            /**
             * Method
             * @default none
             */
            method: string;
            /** Quote */
            quote: string;
            /** Sectionid */
            sectionId: string | null;
            /** Start */
            start: number;
            /** Verified */
            verified: boolean;
        };
        /** StageOut */
        StageOut: {
            /** At */
            at: string;
            /** Attempt */
            attempt?: number | null;
            /** Completedat */
            completedAt?: string | null;
            /** Detail */
            detail?: string | null;
            /** Durationms */
            durationMs?: number | null;
            /** Errorcode */
            errorCode?: string | null;
            /** Inputhash */
            inputHash?: string | null;
            /** Outputhash */
            outputHash?: string | null;
            /**
             * Stage
             * @enum {string}
             */
            stage: "reading" | "finding_evidence" | "checking" | "verifying" | "complete" | "unresolved" | "failed";
            /** Status */
            status?: ("running" | "ok" | "failed") | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    batches_api_batches_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchSummary"][];
                };
            };
        };
    };
    batch_api_batches__batch_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batch_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    batch_values_csv_api_batches__batch_id__values_csv_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batch_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_documents_api_documents_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentSummary"][];
                };
            };
        };
    };
    upload_document_api_documents_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_document_api_documents_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_api_documents__document_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    citations_api_engineering_citations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CitationRecordOut"];
                };
            };
        };
    };
    experiments_api_engineering_experiments_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentsOut"];
                };
            };
        };
    };
    families_api_engineering_families_get: {
        parameters: {
            query?: {
                threshold?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FamiliesOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    goldens_api_engineering_goldens_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoldensOut"];
                };
            };
        };
    };
    list_findings_api_findings_get: {
        parameters: {
            query?: {
                documentId?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindingRecord"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_api_findings__finding_id__review_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                finding_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindingReviewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_guidance_api_guidance_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GuidanceIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GuidanceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_guidance_api_guidance__guidance_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                guidance_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GuidanceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    create_memo_api_memos_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemoIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    memo_as_docx_api_memos__memo_id__docx_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                memo_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    memo_as_html_api_memos__memo_id__html_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                memo_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_api_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSummary"][];
                };
            };
        };
    };
    create_run_api_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_detail_api_runs__run_id__detail_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_events_api_runs__run_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    evidence_pack_api_runs__run_id__evidence_pack_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
