"""Sequences of operations against the API, generated by Hypothesis, with the record's invariants checked
after every step. Single-path tests show each rule once; this shows that no order of uploads, questions,
reviews, undos and memos breaks them.

Invariants:
- a finished run never changes: stage, findings, spans and raw output are what they were when first seen;
- the same inputs give the same run while that run is not failed (idempotency);
- every verified span, read back from the stored section text at its offsets, has the quote's letters and digits;
- a memo asked twice for the same run is the same memo;
- a review is the latest verdict, and clearing it returns the finding to unreviewed.
"""

from __future__ import annotations

from typing import Any

from fastapi.testclient import TestClient
from hypothesis import settings
from hypothesis import strategies as st
from hypothesis.stateful import RuleBasedStateMachine, initialize, invariant, rule, run_state_machine_as_test

from app.verify.spans import alnum_with_map
from tests.support import CONTRACT, FUZZ_SCALE, GUIDANCE

SECOND_CONTRACT = CONTRACT.replace("Nevada", "Delaware").replace("thirty (30)", "sixty (60)")
QUESTIONS = (
    "On what grounds and with how much notice may a party terminate this agreement?",
    "What law governs this agreement and where must disputes be brought?",
    "What is the cap on each party's liability?",
)
TERMINAL = ("complete", "unresolved", "failed")


def letters_and_digits(text: str) -> str:
    return alnum_with_map(text)[0]


def test_operation_sequences_keep_the_record_s_invariants(client: TestClient) -> None:
    class Workbench(RuleBasedStateMachine):
        def __init__(self) -> None:
            super().__init__()
            self.documents: list[str] = []
            self.sections: dict[str, dict[str, str]] = {}
            self.guidance_id: str | None = None
            self.runs: dict[str, dict[str, Any]] = {}  # run id -> snapshot when first seen finished
            self.by_inputs: dict[tuple[str, str | None, str], str] = {}
            self.memos: dict[str, str] = {}

        @initialize()
        def upload(self) -> None:
            for name, text in (("a.txt", CONTRACT), ("b.txt", SECOND_CONTRACT)):
                response = client.post("/api/documents", files={"file": (name, text.encode("utf-8"), "text/plain")})
                assert response.status_code in (200, 201), response.text
                document = response.json()
                self.documents.append(document["id"])
                full = client.get(f"/api/documents/{document['id']}").json()
                self.sections[document["id"]] = {s["id"]: s["text"] for s in full["sections"]}

        def _run(self, run_id: str) -> dict[str, Any]:
            response = client.get(f"/api/runs/{run_id}")
            assert response.status_code == 200, response.text
            run: dict[str, Any] = response.json()
            return run

        @rule(document=st.integers(min_value=0, max_value=1), question=st.sampled_from(QUESTIONS), with_guidance=st.booleans())
        def ask(self, document: int, question: str, with_guidance: bool) -> None:
            if with_guidance and self.guidance_id is None:
                created = client.post("/api/guidance", json={"text": GUIDANCE})
                assert created.status_code in (200, 201)
                self.guidance_id = created.json()["id"]
            document_id = self.documents[document]
            guidance_id = self.guidance_id if with_guidance else None
            response = client.post("/api/runs", json={"documentId": document_id, "guidanceId": guidance_id, "question": question})
            assert response.status_code in (200, 202), response.text
            run_id = response.json()["id"]
            key = (document_id, guidance_id, question)
            earlier = self.by_inputs.get(key)
            if earlier is not None and self.runs.get(earlier, {}).get("stage") != "failed":
                assert run_id == earlier, "the same inputs must return the existing run"
                assert response.status_code == 200 and response.json()["reused"] is True
            self.by_inputs[key] = run_id
            self._remember(run_id)

        def _remember(self, run_id: str) -> None:
            run = self._run(run_id)
            if run["stage"] in TERMINAL and run_id not in self.runs:
                self.runs[run_id] = {
                    "stage": run["stage"],
                    "findings": [
                        (f["id"], f["status"], [(s["sectionId"], s["start"], s["end"], s["verified"], s["quote"]) for s in f["spans"]]) for f in run["findings"]
                    ],
                    "documentId": run.get("documentId"),
                }

        @rule(pick=st.integers(min_value=0, max_value=50), verdict=st.sampled_from(["confirmed", "dismissed", "cleared"]))
        def review(self, pick: int, verdict: str) -> None:
            findings = [f for snapshot in self.runs.values() for f in snapshot["findings"] if snapshot["stage"] == "complete"]
            if not findings:
                return
            finding_id = findings[pick % len(findings)][0]
            response = client.post(f"/api/findings/{finding_id}/review", json={"verdict": verdict, "reviewer": "hypothesis"})
            assert response.status_code in (200, 201), response.text
            shown = response.json()
            if verdict == "cleared":
                assert shown.get("review") in (None, {}) or shown["review"].get("verdict") in (None, "cleared")
            else:
                assert shown["review"]["verdict"] == verdict

        @rule(pick=st.integers(min_value=0, max_value=50))
        def memo(self, pick: int) -> None:
            complete = [run_id for run_id, snapshot in self.runs.items() if snapshot["stage"] == "complete"]
            if not complete:
                return
            run_id = complete[pick % len(complete)]
            response = client.post("/api/memos", json={"runId": run_id})
            assert response.status_code in (200, 201), response.text
            memo_id = response.json()["id"]
            if run_id in self.memos:
                assert self.memos[run_id] == memo_id, "a memo asked twice is the same memo"
            self.memos[run_id] = memo_id

        @invariant()
        def finished_runs_do_not_change(self) -> None:
            for run_id, snapshot in self.runs.items():
                run = self._run(run_id)
                assert run["stage"] == snapshot["stage"]
                now = [(f["id"], f["status"], [(s["sectionId"], s["start"], s["end"], s["verified"], s["quote"]) for s in f["spans"]]) for f in run["findings"]]
                assert now == snapshot["findings"], f"run {run_id} changed after finishing"

        @invariant()
        def verified_spans_read_back_as_their_quotes(self) -> None:
            for run_id in self.runs:
                run = self._run(run_id)
                sections = self.sections.get(run.get("documentId", ""), {})
                if not sections:
                    sections = {sid: text for per_doc in self.sections.values() for sid, text in per_doc.items()}
                for finding in run["findings"]:
                    for span in finding["spans"]:
                        if span["verified"]:
                            text = sections[span["sectionId"]][span["start"] : span["end"]]
                            assert letters_and_digits(text) == letters_and_digits(span["quote"])

    Workbench.TestCase.settings = settings(max_examples=6 * FUZZ_SCALE, stateful_step_count=10 * min(FUZZ_SCALE, 3), deadline=None)
    run_state_machine_as_test(Workbench, settings=Workbench.TestCase.settings)  # type: ignore[no-untyped-call]
